CREATE TABLE [dbo].[SYSTEM_MEMBER_LOGIN_ATTEMPTS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[UN] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PW] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Success] [bit] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_LOGIN_ATTEMPTS_Success] DEFAULT ((0)),
[DateAdded] [datetime] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_LOGIN_ATTEMPTS_DateAdded] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_MEMBER_LOGIN_ATTEMPTS] ADD CONSTRAINT [PK_SYSTEM_MEMBER_LOGIN_ATTEMPTS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
