CREATE TABLE [dbo].[SYSTEM_CONFIGURATION_DATA_PLUGINS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Template_ID] [uniqueidentifier] NOT NULL,
[Interface] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DLL_FileName] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_Class_Name] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Plugin_Arguments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Once] [bit] NOT NULL,
[DateAdded] [datetime] NOT NULL,
[DateModified] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_CONFIGURATION_DATA_PLUGINS] ADD CONSTRAINT [PK_ID_SYSTEM_CONFIGURATION_DATA_PLUGINS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_CONFIGURATION_DATA_PLUGINS] ADD CONSTRAINT [FK_SYSTEM_CONFIGURATION_DATA_PLUGINS_SYSTEM_CONFIGURATION_DATA_TEMPLATES] FOREIGN KEY ([Template_ID]) REFERENCES [dbo].[SYSTEM_CONFIGURATION_DATA_TEMPLATES] ([ID])
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'SYSTEM_TABLES', 'SCHEMA', N'dbo', 'TABLE', N'SYSTEM_CONFIGURATION_DATA_PLUGINS', NULL, NULL
GO
