CREATE TABLE [dbo].[SYSTEM_PLUGIN_EXTENDED_PERMISSIONS]
(
[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_SYSTEM_PLUGIN_EXTENDED_PERMISSIONS_ID] DEFAULT (newid()),
[Plugin_ID] [uniqueidentifier] NOT NULL,
[Application_ID] [uniqueidentifier] NOT NULL,
[IsDefaultPlugin] [bit] NOT NULL CONSTRAINT [DF_Table_1_Default] DEFAULT ((0)),
[Choosable] [bit] NOT NULL CONSTRAINT [DF_SYSTEM_PLUGIN_EXTENDED_PERMISSIONS_Choosable] DEFAULT ((0)),
[DateAdded] [datetime] NOT NULL CONSTRAINT [DF_SYSTEM_PLUGIN_EXTENDED_PERMISSIONS_DateAdded] DEFAULT (getdate()),
[DateModified] [datetime] NOT NULL CONSTRAINT [DF_SYSTEM_PLUGIN_EXTENDED_PERMISSIONS_DateModified] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_PLUGIN_EXTENDED_PERMISSIONS] ADD CONSTRAINT [PK_SYSTEM_PLUGIN_EXTENDED_PERMISSIONS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'SYSTEM_TABLES', 'SCHEMA', N'dbo', 'TABLE', N'SYSTEM_PLUGIN_EXTENDED_PERMISSIONS', NULL, NULL
GO
