CREATE TABLE [dbo].[SYSTEM_MENU_CLIENT_PERMISSIONS]
(
[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_SYSTEM_MENU_CLIENT_PERMISSIONS_ID] DEFAULT (newid()),
[Menu_ID] [uniqueidentifier] NULL,
[Page_ID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_SYSTEM_MENU_CLIENT_PERMISSIONS_Page_ID] DEFAULT ('DEFAULT'),
[Client_ID] [uniqueidentifier] NULL,
[Member_ID] [uniqueidentifier] NULL,
[Client_Permission_Group_ID] [int] NULL,
[Client_Admin] [bit] NOT NULL CONSTRAINT [DF_SYSTEM_MENU_CLIENT_PERMISSIONS_Client_Admin] DEFAULT ((0)),
[DateAdded] [datetime] NOT NULL CONSTRAINT [DF_SYSTEM_MENU_CLIENT_PERMISSIONS_DateAdded] DEFAULT (getdate()),
[DateModified] [datetime] NOT NULL CONSTRAINT [DF_SYSTEM_MENU_CLIENT_PERMISSIONS_DateModified] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_MENU_CLIENT_PERMISSIONS] ADD CONSTRAINT [PK_SYSTEM_MENU_CLIENT_PERMISSIONS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_MENU_CLIENT_PERMISSIONS] ADD CONSTRAINT [FK_SYSTEM_MENU_CLIENT_PERMISSIONS_Client_Permission_Groups] FOREIGN KEY ([Client_Permission_Group_ID]) REFERENCES [dbo].[Client_Permission_Groups] ([ID])
GO
ALTER TABLE [dbo].[SYSTEM_MENU_CLIENT_PERMISSIONS] ADD CONSTRAINT [FK_SYSTEM_MENU_CLIENT_PERMISSIONS_Clients] FOREIGN KEY ([Client_ID]) REFERENCES [dbo].[Clients] ([ID])
GO
ALTER TABLE [dbo].[SYSTEM_MENU_CLIENT_PERMISSIONS] ADD CONSTRAINT [FK_SYSTEM_MENU_CLIENT_PERMISSIONS_Members] FOREIGN KEY ([Member_ID]) REFERENCES [dbo].[Members] ([ID])
GO
ALTER TABLE [dbo].[SYSTEM_MENU_CLIENT_PERMISSIONS] ADD CONSTRAINT [FK_SYSTEM_MENU_CLIENT_PERMISSIONS_SYSTEM_MENUS] FOREIGN KEY ([Menu_ID]) REFERENCES [dbo].[SYSTEM_MENUS] ([ID])
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'SYSTEM_TABLES', 'SCHEMA', N'dbo', 'TABLE', N'SYSTEM_MENU_CLIENT_PERMISSIONS', NULL, NULL
GO
