CREATE TABLE [dbo].[SYSTEM_MEMBER_ACCOUNT_STATUS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Priority] [int] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_ACCOUNT_STATUS_Priority] DEFAULT ((1)),
[AllOK] [bit] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_ACCOUNT_STATUS_AllOK] DEFAULT ((1)),
[Locked] [bit] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_ACCOUNT_STATUS_Locked] DEFAULT ((0)),
[Deleted] [bit] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_ACCOUNT_STATUS_Deleted] DEFAULT ((0)),
[DateAdded] [datetime] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_ACCOUNT_STATUS_DateAdded] DEFAULT (getdate()),
[DateModified] [datetime] NOT NULL CONSTRAINT [DF_SYSTEM_MEMBER_ACCOUNT_STATUS_DateModified] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_MEMBER_ACCOUNT_STATUS] ADD CONSTRAINT [PK_SYSTEM_MEMBER_ACCOUNT_STATUS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'SYSTEM_TABLES', 'SCHEMA', N'dbo', 'TABLE', N'SYSTEM_MEMBER_ACCOUNT_STATUS', NULL, NULL
GO
