CREATE TABLE [dbo].[SYSTEM_PLUGIN_ARGUMENTS]
(
[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_SYSTEM_PLUGIN_ARGUMENTS_ID] DEFAULT (newid()),
[Plugin_ID] [uniqueidentifier] NOT NULL,
[Argument] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_Table_1_IsDefault] DEFAULT ((1)),
[DisplayOrder] [int] NOT NULL CONSTRAINT [DF_SYSTEM_PLUGIN_ARGUMENTS_DisplayOrder] DEFAULT ((1)),
[DateAdded] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_PLUGIN_ARGUMENTS] ADD CONSTRAINT [PK_SYSTEM_PLUGIN_ARGUMENTS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_PLUGIN_ARGUMENTS] ADD CONSTRAINT [FK_SYSTEM_PLUGIN_ARGUMENTS_SYSTEM_PLUGINS] FOREIGN KEY ([Plugin_ID]) REFERENCES [dbo].[SYSTEM_PLUGINS] ([ID])
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'SYSTEM_TABLES', 'SCHEMA', N'dbo', 'TABLE', N'SYSTEM_PLUGIN_ARGUMENTS', NULL, NULL
GO
