CREATE TABLE [dbo].[SYSTEM_COMPLEX_SETTINGS]
(
[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_SYSTEM_COMPLEX_SETTINGS_ID] DEFAULT (newid()),
[Name] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GroupName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Encryption_Key_ID] [uniqueidentifier] NULL,
[DateAdded] [datetime] NOT NULL,
[DateModified] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_COMPLEX_SETTINGS] ADD CONSTRAINT [PK_SYSTEM_COMPLEX_SETTINGS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_COMPLEX_SETTINGS] ADD CONSTRAINT [FK_SYSTEM_COMPLEX_SETTINGS_SYSTEM_ENCRYPTION_KEYS] FOREIGN KEY ([Encryption_Key_ID]) REFERENCES [dbo].[SYSTEM_ENCRYPTION_KEYS] ([ID])
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'SYSTEM_TABLES', 'SCHEMA', N'dbo', 'TABLE', N'SYSTEM_COMPLEX_SETTINGS', NULL, NULL
GO
