CREATE TABLE [dbo].[SYSTEM_INTERFACE_PLUGINS]
(
[ID] [uniqueidentifier] NOT NULL,
[Interface_ID] [uniqueidentifier] NOT NULL,
[Plugin_ID] [uniqueidentifier] NOT NULL,
[IsDefault] [bit] NOT NULL CONSTRAINT [DF_SYSTEM_INTERFACE_PLUGINS_IsDefault] DEFAULT ((1)),
[DateAdded] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_INTERFACE_PLUGINS] ADD CONSTRAINT [PK_SYSTEM_INTERFACE_PLUGINS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYSTEM_INTERFACE_PLUGINS] ADD CONSTRAINT [FK_SYSTEM_INTERFACE_PLUGINS_SYSTEM_INTERFACES] FOREIGN KEY ([Interface_ID]) REFERENCES [dbo].[SYSTEM_INTERFACES] ([ID])
GO
ALTER TABLE [dbo].[SYSTEM_INTERFACE_PLUGINS] ADD CONSTRAINT [FK_SYSTEM_INTERFACE_PLUGINS_SYSTEM_PLUGINS] FOREIGN KEY ([Plugin_ID]) REFERENCES [dbo].[SYSTEM_PLUGINS] ([ID])
GO
EXEC sp_addextendedproperty N'VirtualFolder', N'SYSTEM_TABLES', 'SCHEMA', N'dbo', 'TABLE', N'SYSTEM_INTERFACE_PLUGINS', NULL, NULL
GO
